#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
ROLLBAR_TOKEN=$(dokku config:get "$APP" ROLLBAR_TOKEN || echo)
ROLLBAR_DEPLOY_ID=$(dokku config:get "$APP" ROLLBAR_DEPLOY_ID || echo "$ROLLBAR_DEPLOY_ID")

if [[ $ROLLBAR_TOKEN ]]; then
  echo "-----> Notifying Rollbar ..."

  ROLLBAR_RESULT=$(curl -XPATCH -s https://api.rollbar.com/api/1/deploy/$ROLLBAR_DEPLOY_ID \
    -H "X-Rollbar-Access-Token:$ROLLBAR_TOKEN" \
    -F status=succeeded
  )

  echo "       ${ROLLBAR_RESULT}"
fi
